# Generated by Django 6.1.1 on 2026-09-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('trip_label', models.CharField(blank=True, max_length=500, verbose_name='الرحلة / الموعد')),
                ('trip_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الرحلة')),
                ('people', models.PositiveIntegerField(default=1, verbose_name='عدد الأفراد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طلب حجز',
                'verbose_name_plural': 'طلبات الحجز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='رحلات الحج والعمرة', max_length=255, verbose_name='اسم الشركة')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='رقم الواتساب بصيغة دولية')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='العنوان')),
                ('facebook', models.URLField(blank=True, verbose_name='رابط صفحة فيسبوك')),
                ('hero_title', models.CharField(default='رحلات الحج والعمرة لكل مواسم السنة', max_length=255)),
                ('hero_sub', models.TextField(default='تعرّف على رحلاتنا بتفاصيل كاملة لأيام السير، من نقطة الخروج حتى العودة، واحجز مكانك في المواعيد المتاحة.')),
                ('hero_btn', models.CharField(default='استكشف رحلات السنة', max_length=100)),
                ('trips_title', models.CharField(default='رحلات السنة', max_length=255)),
                ('trips_sub', models.TextField(default='جميع رحلات الحج والعمرة مرتبة حسب موعد الانطلاق، اضغط على أي رحلة لعرض برنامج السير بالتفصيل من الخروج حتى العودة.')),
                ('why_title', models.CharField(default='لماذا تختارنا؟', max_length=255)),
                ('cta_title', models.CharField(default='جاهز تبدأ رحلتك المباركة؟', max_length=255)),
                ('cta_sub', models.TextField(default='تواصل معنا الآن واحجز مكانك في أقرب رحلة.')),
                ('section_order', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'بيانات الموقع',
                'verbose_name_plural': 'بيانات الموقع',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الرحلة')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='الرابط')),
                ('trip_type', models.CharField(choices=[('hajj', 'الحج'), ('umrah', 'العمرة'), ('ramadan', 'عمرة رمضان')], default='umrah', max_length=20, verbose_name='نوع الرحلة')),
                ('description', models.TextField(blank=True, verbose_name='نبذة عن الرحلة')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعر (بالجنيه)')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='المدة')),
                ('departure', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة')),
                ('transport', models.CharField(blank=True, max_length=50, verbose_name='وسيلة النقل')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='الطاقة الاستيعابية')),
                ('remaining', models.PositiveIntegerField(blank=True, null=True, verbose_name='الأماكن المتبقية')),
                ('is_active', models.BooleanField(default=True, verbose_name='معروضة على الموقع')),
                ('itinerary', models.JSONField(default=list, verbose_name='برنامج السير')),
                ('includes', models.JSONField(default=list, verbose_name='يشمل السعر')),
                ('excludes', models.JSONField(default=list, verbose_name='لا يشمل السعر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'الرحلات',
                'ordering': ['departure', 'name'],
            },
        ),
    ]
