# Generated by Django 6.1.1 on 2026-09-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trip_price_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='trip_thumbnails/%Y/%m/', verbose_name='صورة الرحلة (الصورة المصغرة)'),
        ),
    ]
