# Generated by Django 6.1.1 on 2026-09-16 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import datetime


def backfill_reference_codes(apps, schema_editor):
    Booking = apps.get_model('core', 'Booking')
    prefix = f'HJ-{datetime.now().year}-'
    counter = 1
    used = set()
    for booking in Booking.objects.order_by('created_at', 'pk'):
        if booking.reference_code and booking.reference_code not in used:
            used.add(booking.reference_code)
            continue
        code = f'{prefix}{counter:04d}'
        while code in used:
            counter += 1
            code = f'{prefix}{counter:04d}'
        booking.reference_code = code
        used.add(code)
        counter += 1
        booking.save(update_fields=['reference_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AddField(
            model_name='booking',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_bookings', to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الحجز'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('confirmed', 'تم التأكيد'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='حالة الحجز'),
        ),
        migrations.RunPython(backfill_reference_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم الحجز'),
        ),
    ]