# Generated by Django 6.1.1 on 2026-09-17 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_confirmed_at_booking_handled_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('country', models.CharField(choices=[('مصر', 'مصر'), ('السعودية', 'السعودية'), ('الإمارات', 'الإمارات'), ('الكويت', 'الكويت'), ('قطر', 'قطر'), ('البحرين', 'البحرين'), ('عُمان', 'عُمان'), ('الأردن', 'الأردن'), ('العراق', 'العراق'), ('اليمن', 'اليمن'), ('سوريا', 'سوريا'), ('لبنان', 'لبنان'), ('فلسطين', 'فلسطين'), ('ليبيا', 'ليبيا'), ('تونس', 'تونس'), ('الجزائر', 'الجزائر'), ('المغرب', 'المغرب'), ('السودان', 'السودان'), ('تركيا', 'تركيا'), ('المملكة المتحدة', 'المملكة المتحدة'), ('ألمانيا', 'ألمانيا'), ('فرنسا', 'فرنسا'), ('الولايات المتحدة', 'الولايات المتحدة'), ('كندا', 'كندا'), ('أستراليا', 'أستراليا')], default='مصر', max_length=100, verbose_name='الدولة')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='صورة العميل')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 نجوم'), (2, '2 نجوم'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم')], verbose_name='التقييم')),
                ('text', models.TextField(verbose_name='نص الرأي')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'منشور'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('rejection_reason', models.CharField(blank=True, max_length=500, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reviews', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'رأي عميل',
                'verbose_name_plural': 'آراء العملاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
