# Generated by Django 6.1.1 on 2026-09-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'رحلة', 'verbose_name_plural': 'الرحلات'},
        ),
        migrations.AddField(
            model_name='trip',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتيب الظهور'),
        ),
    ]
