# Generated by Django 6.1.1 on 2026-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_trip_options_trip_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company',
            field=models.CharField(default='الطوخي فلاي', max_length=255, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='رحلتك الروحانية تبدأ من هنا', max_length=255),
        ),
    ]
