# Generated by Django 6.1.1 on 2026-09-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان الملف')),
                ('file', models.ImageField(upload_to='dashboard/%Y/%m/', verbose_name='الملف')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='النص البديل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'ملف وسائط',
                'verbose_name_plural': 'مكتبة الوسائط',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
